// Package api wrap the Vault REST API. This is currently not autogenerated.
//
// Background: We started with a hand-written client, but wanted to switch to a
// generated one, for saving on boilerplate. In 2024, vault openapi schema
// changed to 3.1.0, but oapi-codegen/oapi-codegen does not support it:
// https://github.com/oapi-codegen/oapi-codegen/issues/373
//
// Options:
//
//  1. use another code generation library (oapi-codegen got good feedback, as for generated code)
//  2. downgrade 3.1.0 -> 3.0.X schema with some tool (maybe flaky), may lose fidelity
//  3. remove codegen altogether and find some efficient way around some of the boilerplate
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math/rand"
	"net/http"
	"net/http/cookiejar"
	"net/http/httputil"
	"net/url"
	"regexp"
	"strings"
	"time"

	"github.com/antchfx/htmlquery"
	"github.com/rclone/rclone/backend/vault/cache"
	"github.com/rclone/rclone/fs"
	"github.com/rclone/rclone/fs/fshttp"
	"github.com/rclone/rclone/lib/rest"
)

const (
	// VaultVersionHeader as served by vault site.
	VaultVersionHeader = "X-Vault-API-Version"
	// VersionSupported is the version of the vault API this package implements.
	VersionSupported = "3"
	// maxResponseBody limit in bytes when reading a response body.
	maxResponseBody = 1 << 24
)

var (
	// ErrUserNotFound when a username is not registered in vault.
	ErrUserNotFound = errors.New("user not found")
	// ErrAmbiguousQuery when we except 0 or 1 result in the result set, but get more.
	ErrAmbiguousQuery = errors.New("ambiguous query")
)

// Error for failed api requests.
type Error struct {
	err error
}

// Error returns a string.
func (e *Error) Error() string {
	return fmt.Sprintf("api error: %v", e.err)
}

// API wraps the Vault API. Django REST Framework has some support for swagger
// definitions, which we may switch over at some point (it was not enabled).
// Most operations will require an authenticated client.
type API struct {
	Endpoint string
	Username string
	Password string
	// VersionSupported by this implementation. This is should checked before
	// any other operation.
	VersionSupported string
	// An rclone helper rest client wrapper.
	client    *rest.Client
	loginPath string
	timeout   time.Duration
	cache     *cache.Cache
}

// New sets up a new api, no further checks (e.g. for api compatibility) at
// this time.
func New(endpoint, username, password string) *API {
	ctx := context.Background()
	// TODO: add retry on a lower level, e.g. via pester or other library
	return &API{
		Endpoint:         endpoint,
		Username:         username,
		Password:         password,
		VersionSupported: VersionSupported,
		client:           rest.NewClient(fshttp.NewClient(ctx)).SetRoot(endpoint),
		loginPath:        "/accounts/login/", // trailing slash required, cf. django APPEND_SLASH
		timeout:          30 * time.Second,
		cache:            cache.New(),
	}
}

func (api *API) Client() *rest.Client {
	return api.client
}

// Version returns the API version supported by the endpoint, transmitted in an
// HTTP header. It returns an empty string, if version could not be determined.
func (api *API) Version(ctx context.Context) string {
	opts := rest.Opts{
		Method: "GET",
		Path:   "/",
	}
	resp, err := api.client.Call(ctx, &opts)
	if err != nil {
		return ""
	}
	defer resp.Body.Close() // nolint:errcheck
	return resp.Header.Get(VaultVersionHeader)
}

// String prints out name and version supported.
func (api *API) String() string {
	return fmt.Sprintf("vault (v%s)", api.VersionSupported)
}

// Login sets up a session, which should be valid for the client until logout
// (or timeout). This follows the interactive login procedure. TODO: move to a
// better auth scheme, e.g. via
// https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication
func (api *API) Login() (err error) {
	var u *url.URL
	if u, err = url.Parse(api.Endpoint); err != nil {
		return err
	}
	u.Path = strings.Replace(u.Path, "/api", api.loginPath, 1)
	loginURL := u.String()
	resp, err := http.Get(loginURL)
	if err != nil {
		return fmt.Errorf("cannot access login url: %w", err)
	}
	defer resp.Body.Close() // nolint:errcheck
	// Parse out the CSRF token: <input type="hidden"
	// name="csrfmiddlewaretoken"
	// value="CCBQ9qqG3ylgR1MaYBc6UCw4tlxR7rhP2Qs4uvIMAf1h7Dd4xtv5azTQJRgJ1y2I">
	//
	// TODO: move to a token based auth for the API:
	// https://stackoverflow.com/q/21317899/89391
	doc, err := htmlquery.Parse(resp.Body)
	if err != nil {
		return fmt.Errorf("html: %w", err)
	}
	token := htmlquery.SelectAttr(
		htmlquery.FindOne(doc, `//input[@name="csrfmiddlewaretoken"]`),
		"value",
	)
	jar, err := cookiejar.New(nil)
	if err != nil {
		return err
	}
	// Need to reparse, api may live on a different path.
	u, err = url.Parse(api.Endpoint)
	if err != nil {
		return err
	}
	jar.SetCookies(u, []*http.Cookie{&http.Cookie{
		Name:  "csrftoken",
		Value: token,
	}})
	client := http.Client{
		Jar:     jar,
		Timeout: api.timeout,
	}
	// We could use PostForm, but we need to set extra headers.
	data := url.Values{}
	data.Set("username", api.Username)
	data.Set("password", api.Password)
	data.Set("csrfmiddlewaretoken", token)
	req, err := http.NewRequest("POST", loginURL, strings.NewReader(data.Encode()))
	if err != nil {
		return fmt.Errorf("login failed: %w", err)
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	// You are seeing this message because this HTTPS site requires a "Referer
	// header" to be sent by your Web browser, but none was sent. This header
	// is required for security reasons, to ensure that your browser is not
	// being hijacked by third parties.
	req.Header.Set("Referer", loginURL)
	b, _ := httputil.DumpRequest(req, true)
	fs.Debugf(api, "login request ----8<----\n%v", string(b))
	fs.Debugf(api, "----8<----\n")
	resp, err = client.Do(req)
	if err != nil {
		return fmt.Errorf("vault login: %w", err)
	}
	defer resp.Body.Close() // nolint:errcheck
	if resp.StatusCode >= 400 {
		b, _ := ioutil.ReadAll(resp.Body)
		fs.LogPrintf(fs.LogLevelError, api, string(b))
		return fmt.Errorf("login failed with: %v", resp.StatusCode)
	}
	b, _ = httputil.DumpResponse(resp, true)
	if bytes.Contains(b, []byte(`Your username and password didn't match`)) {
		return fmt.Errorf("username and password did not match")
	}
	if len(jar.Cookies(u)) < 2 {
		msg := "expected at least two cookies for session"
		fs.Debugf(api, msg)
		return fmt.Errorf("%v", msg)
	}
	api.client.SetCookie(jar.Cookies(u)...)
	return nil
}

// Logout drops the session.
func (api *API) Logout() {
	_ = api.client.SetHeader("Cookie", "")
}

// Call exposes the current client to the outside, so the caller can reuse
// the autheticated client.
func (api *API) Call(ctx context.Context, opts *rest.Opts) (*http.Response, error) {
	return api.client.Call(ctx, opts)
}

// CallJSON exposes the current client to the outside, so the caller can reuse
// the autheticated client.
func (api *API) CallJSON(ctx context.Context, opts *rest.Opts, req, resp interface{}) (*http.Response, error) {
	return api.client.CallJSON(ctx, opts, req, resp)
}

// SplitPath returns the treenodes for the collection and leaf object for a
// given absolute path as well as the path without the collection. It is an
// error if the collection cannot be found.
func (api *API) SplitPath(p string) (*PathInfo, error) {
	if !strings.HasPrefix(p, "/") {
		return nil, fmt.Errorf("absolute path required: %v", p)
	}
	var (
		err   error
		pi    PathInfo
		parts = strings.Split(p, "/")
	)
	switch {
	case len(parts) < 2:
		return nil, fmt.Errorf("invalid path: %v, expected at least to path segments: %v", p, parts)
	default:
		pi.CollectionTreeNode, err = api.ResolvePath("/" + parts[0])
		if err != nil {
			return nil, err
		}
		pi.LeafTreeNode, err = api.ResolvePath(p)
		if err != nil {
			return nil, err
		}
		pi.RelativePath = strings.Join(parts[2:], "/")
		if pi.RelativePath == "" {
			pi.RelativePath = "/"
		}
	}
	return &pi, nil
}

// ResolvePath resolves an absolute path to a treenode object.
func (api *API) ResolvePath(p string) (*TreeNode, error) {
	if v := api.cache.GetGroup("resolve", p); v != nil {
		return v.(*TreeNode), nil
	}
	t, err := api.root()
	if err != nil {
		return nil, err
	}
	// This method only resolves absolute paths. TODO: Should we rather fail?
	if !strings.HasPrefix(p, "/") {
		p = "/" + p
	}
	// segments: /a/b/c -> [a b c], /a/b/ -> [a b]
	segments := strings.Split(strings.TrimRight(p, "/"), "/")[1:]
	if p != "" && p != "/" && len(segments) == 0 {
		return nil, fs.ErrorObjectNotFound
	}
	for len(segments) > 0 {
		// TODO: when looking up weird names, like " ' @ < > & ? + ≠ from the
		// PutFiles integration test, we fail to look up the value in the API;
		// cf. https://go.dev/play/p/U1zkX4N4iKR
		//
		// However, the rest.Opts parameters use vs.Encode(), which should take
		// care of most of the issues.
		ts, err := api.FindTreeNodes(url.Values{
			"parent": []string{fmt.Sprintf("%d", t.ID)},
			"name":   []string{segments[0]}, // XXX: account for special chars
		})
		switch {
		case err != nil:
			return nil, err
		case len(ts) == 0:
			return nil, fs.ErrorObjectNotFound
		case len(ts) > 1:
			return nil, ErrAmbiguousQuery
		}
		t, segments = ts[0], segments[1:]
	}
	fs.Debugf(api, "resolved path to treenode: %v => %v", p, t.ID)
	api.cache.SetGroup("resolve", p, t)
	return t, nil
}

// DepositStatus returns information about a specific deposit.
func (api *API) DepositStatus(id int64) (*DepositStatus, error) {
	opts := rest.Opts{
		Method: "GET",
		Path:   "/deposit_status",
		Parameters: url.Values{
			"deposit_id": []string{fmt.Sprintf("%d", id)},
		},
	}
	var ds DepositStatus
	resp, err := api.client.CallJSON(context.TODO(), &opts, nil, &ds)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close() // nolint:errcheck
	return &ds, nil
}

// CreateCollection creates a collection with a given name. This would
// corresponds to a directory in the root of a mount.
func (api *API) CreateCollection(ctx context.Context, name string) error {
	fs.Debugf(api, "creating collection %v", name)
	opts := rest.Opts{
		Method:      "POST",
		Path:        "/collections/",
		Body:        strings.NewReader(fmt.Sprintf(`{"name": %q}`, name)),
		ContentType: "application/json",
		ExtraHeaders: map[string]string{
			"X-CSRFTOKEN": api.csrfToken(ctx),
			"Referer":     api.refererURL("collections"),
		},
	}
	fs.Debugf(api, "creating collection with opts: %+v", opts)
	resp, err := api.client.CallJSON(ctx, &opts, nil, nil)
	if err != nil {
		return err
	}
	b, _ := io.ReadAll(resp.Body)
	fs.Debugf(api, "collection created: %v", string(b))
	return resp.Body.Close()
}

// CreateFolder creates a folder below a given parent treenode.
func (api *API) CreateFolder(ctx context.Context, parent *TreeNode, name string) error {
	fs.Debugf(api, "creating folder %v with parent %v", name, parent.ID)
	parentURL := fmt.Sprintf("%s/treenodes/%d/", api.Endpoint, parent.ID)
	opts := rest.Opts{
		Method: "POST",
		Path:   "/treenodes/",
		Body: strings.NewReader(fmt.Sprintf(`{
			"name": %q,
		    "node_type": "FOLDER",
		    "parent": %q
		}`, name, parentURL)),
		ContentType: "application/json",
		ExtraHeaders: map[string]string{
			"X-CSRFTOKEN": api.csrfToken(ctx),
			"Referer":     api.refererURL("treenodes"),
		},
	}
	resp, err := api.client.CallJSON(ctx, &opts, nil, nil)
	if err != nil {
		return err
	}
	return resp.Body.Close()
}

// SetModTime set the modification time.
func (api *API) SetModTime(ctx context.Context, t *TreeNode) error {
	// Hack around immutable "modified_at" field, set the parent to the same value.
	fs.Debugf(api, "set mod time for %v (%d)", t.Name, t.ID)
	opts := rest.Opts{
		Method: "PATCH",
		Path:   fmt.Sprintf("/treenodes/%d/", t.ID),
		ExtraHeaders: map[string]string{
			"X-CSRFTOKEN": api.csrfToken(ctx),
			"Referer":     api.refererURL("treenodes"),
		},
	}
	payload := struct {
		Name string `json:"name"`
	}{
		Name: t.Name + fmt.Sprintf("-%d", rand.Intn(9_999_999)),
	}
	resp, err := api.client.CallJSON(ctx, &opts, payload, nil)
	if err != nil {
		return err
	}
	return resp.Body.Close()
}

// Rename updates name of a treenode.
func (api *API) Rename(ctx context.Context, t *TreeNode, name string) error {
	fs.Debugf(api, "rename %v to %v", t.Name, name)
	opts := rest.Opts{
		Method: "PATCH",
		Path:   fmt.Sprintf("/treenodes/%d/", t.ID),
		ExtraHeaders: map[string]string{
			"X-CSRFTOKEN": api.csrfToken(ctx),
			"Referer":     api.refererURL("treenodes"),
		},
	}
	payload := struct {
		Name string `json:"name"`
	}{
		Name: name,
	}
	resp, err := api.client.CallJSON(ctx, &opts, payload, nil)
	if err != nil {
		return err
	}
	return resp.Body.Close()
}

// Move sets the new parent of t to newParent.
func (api *API) Move(ctx context.Context, t, newParent *TreeNode) error {
	fs.Debugf(api, "move %v under %v", t.Name, newParent.Name)
	opts := rest.Opts{
		Method: "PATCH",
		Path:   fmt.Sprintf("/treenodes/%d/", t.ID),
		ExtraHeaders: map[string]string{
			"X-CSRFTOKEN": api.csrfToken(ctx),
			"Referer":     api.refererURL("treenodes"),
		},
	}
	payload := struct {
		Parent string `json:"parent"`
	}{
		Parent: newParent.URL,
	}
	resp, err := api.client.CallJSON(ctx, &opts, &payload, nil)
	if err != nil {
		return err
	}
	return resp.Body.Close()
}

// Remove a treenode.
func (api *API) Remove(ctx context.Context, t *TreeNode) error {
	opts := rest.Opts{
		Method: "DELETE",
		Path:   fmt.Sprintf("/treenodes/%d/", t.ID),
		ExtraHeaders: map[string]string{
			"X-CSRFTOKEN": api.csrfToken(ctx),
			"Referer":     api.refererURL("treenodes"),
		},
	}
	fs.Debugf(api, "removing %v", t.ID)
	resp, err := api.client.Call(ctx, &opts)
	if err != nil {
		return err
	}
	return resp.Body.Close()
}

// List returns the immediate children of a treenode.
func (api *API) List(t *TreeNode) ([]*TreeNode, error) {
	if t == nil {
		return nil, nil
	}
	return api.FindTreeNodes(url.Values{
		"parent": []string{fmt.Sprintf("%d", t.ID)},
	})
}

// RegisterDeposit sends a RegisterDepositRequest to the API and returns the deposit id.
func (api *API) RegisterDeposit(ctx context.Context, rdr *RegisterDepositRequest) (id int64, err error) {
	opts := rest.Opts{
		Method: "POST",
		Path:   "/register_deposit",
	}
	var depositResp RegisterDepositResponse
	resp, err := api.client.CallJSON(ctx, &opts, rdr, &depositResp)
	if err != nil {
		// Refs. WT-1841, "It will return resp if at all possible, even if err
		// is set", but it may be nil, still.
		if resp != nil && resp.StatusCode == 500 {
			// This may happen, if after a successful, but not yet assembled
			// deposit the same (e.g. sync) command is executed again. This
			// leads to various integrity errors. However, once the files are
			// assembled and in place, the command will work fine again.
			fs.Debugf(api, "got an HTTP 500 while registering a deposit (may be clashing filenames)")
			return 0, &Error{fmt.Errorf("cannot create deposit (probably name clashes); try to use --ignore-existing flag when uploading")}
		}
		// TODO: we need warning deposit here to check whether files already
		// exist; do some kind of "--force" by default
		return 0, &Error{err}
	}
	defer resp.Body.Close() // nolint:errcheck
	fs.Logf(api, "deposit registered: %v", depositResp.ID)
	return depositResp.ID, nil
}

// TreeNodeToCollection turns a treenode to a collection.
func (api *API) TreeNodeToCollection(t *TreeNode) (*Collection, error) {
	result, err := api.FindCollections(url.Values{
		"tree_node": []string{fmt.Sprintf("%d", t.ID)},
	})
	if err != nil {
		return nil, err
	}
	if len(result) == 0 {
		return nil, fmt.Errorf("collection not found")
	}
	return result[0], nil
}

// User returns the current user.
func (api *API) User() (*User, error) {
	fs.Debugf(api, "finding current username")
	userList, err := api.FindUsers(url.Values{
		"username": []string{api.Username},
	})
	switch {
	case err != nil:
		return nil, err
	case len(userList) == 0:
		return nil, ErrUserNotFound
	case len(userList) > 1:
		return nil, ErrAmbiguousQuery
	}
	return userList[0], nil
}

// Organization returns the Organization of the current user.
func (api *API) Organization() (*Organization, error) {
	u, err := api.User()
	if err != nil {
		return nil, fmt.Errorf("failed to get user: %w", err)
	}
	return api.GetOrganization(u.OrganizationIdentifier())
}

// Plan for the current user.
func (api *API) Plan() (*Plan, error) {
	organization, err := api.Organization()
	if err != nil {
		return nil, err
	}
	return api.GetPlan(organization.PlanIdentifier())
}

// refererURL returns a URL that passes as referer, suffix is "collection",
// "treenode", ...
func (api *API) refererURL(suffix string) string {
	return fmt.Sprintf("%s/%s", strings.TrimRight(api.Endpoint, "/"), suffix)
}

// csrfToken retrieves a CSRF token. Returns an empty string on failure.
func (api *API) csrfToken(ctx context.Context) string {
	fs.Debug(api, "csrfToken request")
	opts := rest.Opts{
		Method: "GET",
		Path:   "/users/", // any valid path should do
		ExtraHeaders: map[string]string{
			"Accept": "text/html",
		},
	}
	resp, err := api.client.Call(ctx, &opts)
	if err != nil {
		return ""
	}
	if resp.StatusCode != 200 {
		fs.Debugf(api, "[csrfToken] request failed with %v", resp.StatusCode)
	}
	defer resp.Body.Close() // nolint:errcheck
	b, err := ioutil.ReadAll(io.LimitReader(resp.Body, maxResponseBody))
	if err != nil {
		return ""
	}
	re := regexp.MustCompile(`"csrfToken":[ ]*"([^"]*)"`)
	if matches := re.FindStringSubmatch(string(b)); len(matches) == 2 {
		return matches[1]
	}
	return ""
}

// root returns the organization treenode for the current API user.
func (api *API) root() (*TreeNode, error) {
	if v := api.cache.GetGroup("root", "default"); v != nil {
		return v.(*TreeNode), nil
	}
	organization, err := api.Organization()
	if err != nil {
		return nil, err
	}
	t, err := api.GetTreeNode(organization.TreeNodeIdentifier())
	if err != nil {
		return nil, err
	}
	api.cache.SetGroup("root", "default", t)
	return t, nil
}

//
// Transition back to manual API, porting the v2 deposit code (wip)
// ================================================================

// One and only one of `parent_node_id` and `collection_id` must be supplied.
type RegisterDepositV2Request struct {
	// CollectionId id of Collection serving as the root of the new Deposit. Must be owned by the requesting User's Organization
	CollectionId *int `json:"collection_id,omitempty"`

	// ParentNodeId id of TreeNode to root the new Deposit. TreeNode must be owned by requesting User's Organization. TreeNode must be of type COLLECTION or FOLDER
	ParentNodeId *int `json:"parent_node_id,omitempty"`
}

// TerminateDepositRequest defines model for TerminateDepositRequest.
type TerminateDepositRequest struct {
	// DepositId ID of target `Deposit`
	DepositId int `json:"depositId"`
}

// FinalizeDepositRequest defines model for FinalizeDepositRequest.
type FinalizeDepositRequest struct {
	// DepositId ID of target `Deposit`
	DepositId int `json:"depositId"`
}

// SendChunkResponse represents the parsed response from SendChunkWithBody
type SendChunkResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r SendChunkResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SendChunkResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// TerminateDepositResponse represents the parsed response from TerminateDeposit
type TerminateDepositResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r TerminateDepositResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TerminateDepositResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// FinalizeDepositResponse represents the parsed response from FinalizeDepositWithResponse
type FinalizeDepositResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r FinalizeDepositResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinalizeDepositResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RegisterDepositV2ResponsePayload struct {
	DepositID int `json:"deposit_id"`
}

// RegisterDepositResponse represents the parsed response from RegisterDepositWithResponse
type RegisterDepositV2Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RegisterDepositV2ResponsePayload
}

// Status returns HTTPResponse.Status
func (r RegisterDepositV2Response) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RegisterDepositV2Response) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// SendChunkWithBody sends a chunk of data to a deposit and returns the parsed response.
func (api *API) SendChunkWithBody(ctx context.Context, contentType string, body io.Reader) (*http.Response, error) {
	opts := rest.Opts{
		Method:      "POST",
		Path:        "/deposits/v2/chunk",
		ContentType: contentType,
		Body:        body,
		ExtraHeaders: map[string]string{
			"X-CSRFTOKEN": api.csrfToken(ctx),
			"Referer":     api.refererURL("deposits"),
		},
	}

	fs.Debugf(api, "sending chunk to deposit")
	resp, err := api.client.Call(ctx, &opts)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// TerminateDeposit terminates a deposit that is in progress and returns the parsed response.
func (api *API) TerminateDeposit(ctx context.Context, body TerminateDepositRequest) (*http.Response, error) {
	opts := rest.Opts{
		Method:      "POST",
		Path:        "/deposits/v2/terminate",
		ContentType: "application/json",
		ExtraHeaders: map[string]string{
			"X-CSRFTOKEN": api.csrfToken(ctx),
			"Referer":     api.refererURL("deposits"),
		},
	}
	fs.Debugf(api, "terminating deposit: %d", body.DepositId)
	resp, err := api.client.CallJSON(ctx, &opts, body, nil)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// FinalizeDepositWithResponse finalizes a deposit and returns the parsed response.
func (api *API) FinalizeDepositWithResponse(ctx context.Context, body FinalizeDepositRequest) (*http.Response, error) {
	opts := rest.Opts{
		Method:      "POST",
		Path:        "/deposits/v2/finalize",
		ContentType: "application/json",
		ExtraHeaders: map[string]string{
			"X-CSRFTOKEN": api.csrfToken(ctx),
			"Referer":     api.refererURL("deposits"),
		},
	}

	fs.Debugf(api, "finalizing deposit: %d", body.DepositId)
	resp, err := api.client.CallJSON(ctx, &opts, body, nil)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// RegisterDepositV2WithResponse sends a deposit registration request and returns the parsed response.
func (api *API) RegisterDepositV2WithResponse(ctx context.Context, body RegisterDepositV2Request) (*RegisterDepositV2Response, error) {
	opts := rest.Opts{
		Method:      "POST",
		Path:        "/deposits/v2/register",
		ContentType: "application/json",
		ExtraHeaders: map[string]string{
			"X-CSRFTOKEN": api.csrfToken(ctx),
			"Referer":     api.refererURL("deposits"),
		},
	}
	fs.Debugf(api, "options: %#v", opts)

	fs.Debugf(api, "registering deposit")
	resp, err := api.client.CallJSON(ctx, &opts, body, nil)
	if err != nil {
		return nil, err
	}

	// Parse the response
	bodyBytes, err := io.ReadAll(resp.Body)
	defer func() { _ = resp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RegisterDepositV2Response{
		Body:         bodyBytes,
		HTTPResponse: resp,
		JSON200:      &RegisterDepositV2ResponsePayload{},
	}
	// If successful response with JSON content, parse it
	if strings.Contains(resp.Header.Get("Content-Type"), "json") && resp.StatusCode == 200 {
		var dest RegisterDepositV2ResponsePayload
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		fs.Debugf(api, "[classic] register deposit response: %v", string(bodyBytes))
		response.JSON200 = &dest
	} else {
		fs.Debugf(api, "unexpected content type or http status: %v, %v", resp.Header.Get("Content-Type"), resp.StatusCode)
	}

	return response, nil
}
