# syntax = docker/dockerfile:experimental
#
# Base image for vault
#
# > cf. https://stackoverflow.com/q/58018300/89391
#
FROM python:3.8.16-slim-bullseye
RUN apt-get update && apt-get install -y --no-install-recommends make build-essential git
WORKDIR /app
COPY . .
RUN --mount=type=cache,target=/root/.cache make clean && make setup

