// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package vault

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/getkin/kin-openapi/openapi3"
)

// FinalizeDepositRequest defines model for FinalizeDepositRequest.
type FinalizeDepositRequest struct {
	// DepositId ID of target `Deposit`
	DepositId int `json:"depositId"`
}

// RegisterDeposit2Request Description of Deposit to register.
//
// One and only one of `parent_node_id` and `collection_id` must be supplied.
type RegisterDeposit2Request struct {
	// CollectionId id of Collection serving as the root of the new Deposit. Must be owned by the requesting User's Organization
	CollectionId *int `json:"collection_id,omitempty"`

	// ParentNodeId id of TreeNode to root the new Deposit. TreeNode must be owned by requesting User's Organization. TreeNode must be of type COLLECTION or FOLDER
	ParentNodeId *int `json:"parent_node_id,omitempty"`
}

// RegisterDeposit2Response Description of the newly registered Deposit
type RegisterDeposit2Response struct {
	DepositId int `json:"deposit_id"`
}

// VaultDepositApiHasChunkParams defines parameters for VaultDepositApiHasChunk.
type VaultDepositApiHasChunkParams struct {
	// DepositId ID of target `Deposit`
	DepositId int `form:"depositId" json:"depositId"`

	// FlowIdentifier Unique identifier of file. Must be a pure function of the file underlying the chunk and globally unique.
	FlowIdentifier string `form:"flowIdentifier" json:"flowIdentifier"`

	// FlowFilename Name of file being uploaded as appearing on user filesystem
	FlowFilename string `form:"flowFilename" json:"flowFilename"`

	// FlowRelativePath Relative path of file as appearing on user filesystem
	FlowRelativePath string `form:"flowRelativePath" json:"flowRelativePath"`

	// FlowChunkNumber 1-based index of the current chunk in the sequence of chunks.
	FlowChunkNumber int `form:"flowChunkNumber" json:"flowChunkNumber"`

	// FlowChunkSize Maximum chunk size in bytes for this file
	FlowChunkSize int `form:"flowChunkSize" json:"flowChunkSize"`

	// FlowCurrentChunkSize size in bytes of the current chunk
	FlowCurrentChunkSize int `form:"flowCurrentChunkSize" json:"flowCurrentChunkSize"`

	// FlowTotalSize size in bytes of file being uploaded
	FlowTotalSize int `form:"flowTotalSize" json:"flowTotalSize"`

	// FlowTotalChunks number of chunks comprising the file
	FlowTotalChunks int `form:"flowTotalChunks" json:"flowTotalChunks"`

	// FlowMimetype user-reported mimetype of file being uploaded
	FlowMimetype string `form:"flowMimetype" json:"flowMimetype"`

	// FlowUserMtime ISO8601-formatted modification time of file on user filesystem
	FlowUserMtime time.Time `form:"flowUserMtime" json:"flowUserMtime"`
}

// VaultDepositApiSendChunkMultipartBody defines parameters for VaultDepositApiSendChunk.
type VaultDepositApiSendChunkMultipartBody struct {
	// DepositId ID of target `Deposit`
	DepositId int `json:"depositId"`

	// File Content of chunk
	File openapi_types.File `json:"file"`

	// FlowChunkNumber 1-based index of the current chunk in the sequence of chunks.
	FlowChunkNumber int `json:"flowChunkNumber"`

	// FlowChunkSize Maximum chunk size in bytes for this file
	FlowChunkSize int `json:"flowChunkSize"`

	// FlowCurrentChunkSize size in bytes of the current chunk
	FlowCurrentChunkSize int `json:"flowCurrentChunkSize"`

	// FlowFilename Name of file being uploaded as appearing on user filesystem
	FlowFilename string `json:"flowFilename"`

	// FlowIdentifier Unique identifier of file. Must be a pure function of the file underlying the chunk and globally unique.
	FlowIdentifier string `json:"flowIdentifier"`

	// FlowMimetype user-reported mimetype of file being uploaded
	FlowMimetype string `json:"flowMimetype"`

	// FlowRelativePath Relative path of file as appearing on user filesystem
	FlowRelativePath string `json:"flowRelativePath"`

	// FlowTotalChunks number of chunks comprising the file
	FlowTotalChunks int `json:"flowTotalChunks"`

	// FlowTotalSize size in bytes of file being uploaded
	FlowTotalSize int `json:"flowTotalSize"`

	// FlowUserMtime ISO8601-formatted modification time of file on user filesystem
	FlowUserMtime time.Time `json:"flowUserMtime"`
}

// VaultDepositApiSendChunkMultipartRequestBody defines body for VaultDepositApiSendChunk for multipart/form-data ContentType.
type VaultDepositApiSendChunkMultipartRequestBody VaultDepositApiSendChunkMultipartBody

// VaultDepositApiFinalizeDepositJSONRequestBody defines body for VaultDepositApiFinalizeDeposit for application/json ContentType.
type VaultDepositApiFinalizeDepositJSONRequestBody = FinalizeDepositRequest

// VaultDepositApiRegisterDepositJSONRequestBody defines body for VaultDepositApiRegisterDeposit for application/json ContentType.
type VaultDepositApiRegisterDepositJSONRequestBody = RegisterDeposit2Request

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// VaultDepositApiHasChunk request
	VaultDepositApiHasChunk(ctx context.Context, params *VaultDepositApiHasChunkParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// VaultDepositApiSendChunk request with any body
	VaultDepositApiSendChunkWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// VaultDepositApiFinalizeDeposit request with any body
	VaultDepositApiFinalizeDepositWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	VaultDepositApiFinalizeDeposit(ctx context.Context, body VaultDepositApiFinalizeDepositJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// VaultDepositApiRegisterDeposit request with any body
	VaultDepositApiRegisterDepositWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	VaultDepositApiRegisterDeposit(ctx context.Context, body VaultDepositApiRegisterDepositJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) VaultDepositApiHasChunk(ctx context.Context, params *VaultDepositApiHasChunkParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVaultDepositApiHasChunkRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) VaultDepositApiSendChunkWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVaultDepositApiSendChunkRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) VaultDepositApiFinalizeDepositWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVaultDepositApiFinalizeDepositRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) VaultDepositApiFinalizeDeposit(ctx context.Context, body VaultDepositApiFinalizeDepositJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVaultDepositApiFinalizeDepositRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) VaultDepositApiRegisterDepositWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVaultDepositApiRegisterDepositRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) VaultDepositApiRegisterDeposit(ctx context.Context, body VaultDepositApiRegisterDepositJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVaultDepositApiRegisterDepositRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewVaultDepositApiHasChunkRequest generates requests for VaultDepositApiHasChunk
func NewVaultDepositApiHasChunkRequest(server string, params *VaultDepositApiHasChunkParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/deposits/v2/chunk")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	queryValues := queryURL.Query()

	if queryFrag, err := runtime.StyleParamWithLocation("form", true, "depositId", runtime.ParamLocationQuery, params.DepositId); err != nil {
		return nil, err
	} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
		return nil, err
	} else {
		for k, v := range parsed {
			for _, v2 := range v {
				queryValues.Add(k, v2)
			}
		}
	}

	if queryFrag, err := runtime.StyleParamWithLocation("form", true, "flowIdentifier", runtime.ParamLocationQuery, params.FlowIdentifier); err != nil {
		return nil, err
	} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
		return nil, err
	} else {
		for k, v := range parsed {
			for _, v2 := range v {
				queryValues.Add(k, v2)
			}
		}
	}

	if queryFrag, err := runtime.StyleParamWithLocation("form", true, "flowFilename", runtime.ParamLocationQuery, params.FlowFilename); err != nil {
		return nil, err
	} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
		return nil, err
	} else {
		for k, v := range parsed {
			for _, v2 := range v {
				queryValues.Add(k, v2)
			}
		}
	}

	if queryFrag, err := runtime.StyleParamWithLocation("form", true, "flowRelativePath", runtime.ParamLocationQuery, params.FlowRelativePath); err != nil {
		return nil, err
	} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
		return nil, err
	} else {
		for k, v := range parsed {
			for _, v2 := range v {
				queryValues.Add(k, v2)
			}
		}
	}

	if queryFrag, err := runtime.StyleParamWithLocation("form", true, "flowChunkNumber", runtime.ParamLocationQuery, params.FlowChunkNumber); err != nil {
		return nil, err
	} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
		return nil, err
	} else {
		for k, v := range parsed {
			for _, v2 := range v {
				queryValues.Add(k, v2)
			}
		}
	}

	if queryFrag, err := runtime.StyleParamWithLocation("form", true, "flowChunkSize", runtime.ParamLocationQuery, params.FlowChunkSize); err != nil {
		return nil, err
	} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
		return nil, err
	} else {
		for k, v := range parsed {
			for _, v2 := range v {
				queryValues.Add(k, v2)
			}
		}
	}

	if queryFrag, err := runtime.StyleParamWithLocation("form", true, "flowCurrentChunkSize", runtime.ParamLocationQuery, params.FlowCurrentChunkSize); err != nil {
		return nil, err
	} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
		return nil, err
	} else {
		for k, v := range parsed {
			for _, v2 := range v {
				queryValues.Add(k, v2)
			}
		}
	}

	if queryFrag, err := runtime.StyleParamWithLocation("form", true, "flowTotalSize", runtime.ParamLocationQuery, params.FlowTotalSize); err != nil {
		return nil, err
	} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
		return nil, err
	} else {
		for k, v := range parsed {
			for _, v2 := range v {
				queryValues.Add(k, v2)
			}
		}
	}

	if queryFrag, err := runtime.StyleParamWithLocation("form", true, "flowTotalChunks", runtime.ParamLocationQuery, params.FlowTotalChunks); err != nil {
		return nil, err
	} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
		return nil, err
	} else {
		for k, v := range parsed {
			for _, v2 := range v {
				queryValues.Add(k, v2)
			}
		}
	}

	if queryFrag, err := runtime.StyleParamWithLocation("form", true, "flowMimetype", runtime.ParamLocationQuery, params.FlowMimetype); err != nil {
		return nil, err
	} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
		return nil, err
	} else {
		for k, v := range parsed {
			for _, v2 := range v {
				queryValues.Add(k, v2)
			}
		}
	}

	if queryFrag, err := runtime.StyleParamWithLocation("form", true, "flowUserMtime", runtime.ParamLocationQuery, params.FlowUserMtime); err != nil {
		return nil, err
	} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
		return nil, err
	} else {
		for k, v := range parsed {
			for _, v2 := range v {
				queryValues.Add(k, v2)
			}
		}
	}

	queryURL.RawQuery = queryValues.Encode()

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewVaultDepositApiSendChunkRequestWithBody generates requests for VaultDepositApiSendChunk with any type of body
func NewVaultDepositApiSendChunkRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/deposits/v2/chunk")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewVaultDepositApiFinalizeDepositRequest calls the generic VaultDepositApiFinalizeDeposit builder with application/json body
func NewVaultDepositApiFinalizeDepositRequest(server string, body VaultDepositApiFinalizeDepositJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewVaultDepositApiFinalizeDepositRequestWithBody(server, "application/json", bodyReader)
}

// NewVaultDepositApiFinalizeDepositRequestWithBody generates requests for VaultDepositApiFinalizeDeposit with any type of body
func NewVaultDepositApiFinalizeDepositRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/deposits/v2/finalize")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewVaultDepositApiRegisterDepositRequest calls the generic VaultDepositApiRegisterDeposit builder with application/json body
func NewVaultDepositApiRegisterDepositRequest(server string, body VaultDepositApiRegisterDepositJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewVaultDepositApiRegisterDepositRequestWithBody(server, "application/json", bodyReader)
}

// NewVaultDepositApiRegisterDepositRequestWithBody generates requests for VaultDepositApiRegisterDeposit with any type of body
func NewVaultDepositApiRegisterDepositRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/deposits/v2/register")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// VaultDepositApiHasChunk request
	VaultDepositApiHasChunkWithResponse(ctx context.Context, params *VaultDepositApiHasChunkParams, reqEditors ...RequestEditorFn) (*VaultDepositApiHasChunkResponse, error)

	// VaultDepositApiSendChunk request with any body
	VaultDepositApiSendChunkWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*VaultDepositApiSendChunkResponse, error)

	// VaultDepositApiFinalizeDeposit request with any body
	VaultDepositApiFinalizeDepositWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*VaultDepositApiFinalizeDepositResponse, error)

	VaultDepositApiFinalizeDepositWithResponse(ctx context.Context, body VaultDepositApiFinalizeDepositJSONRequestBody, reqEditors ...RequestEditorFn) (*VaultDepositApiFinalizeDepositResponse, error)

	// VaultDepositApiRegisterDeposit request with any body
	VaultDepositApiRegisterDepositWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*VaultDepositApiRegisterDepositResponse, error)

	VaultDepositApiRegisterDepositWithResponse(ctx context.Context, body VaultDepositApiRegisterDepositJSONRequestBody, reqEditors ...RequestEditorFn) (*VaultDepositApiRegisterDepositResponse, error)
}

type VaultDepositApiHasChunkResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r VaultDepositApiHasChunkResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r VaultDepositApiHasChunkResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type VaultDepositApiSendChunkResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r VaultDepositApiSendChunkResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r VaultDepositApiSendChunkResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type VaultDepositApiFinalizeDepositResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r VaultDepositApiFinalizeDepositResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r VaultDepositApiFinalizeDepositResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type VaultDepositApiRegisterDepositResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RegisterDeposit2Response
}

// Status returns HTTPResponse.Status
func (r VaultDepositApiRegisterDepositResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r VaultDepositApiRegisterDepositResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// VaultDepositApiHasChunkWithResponse request returning *VaultDepositApiHasChunkResponse
func (c *ClientWithResponses) VaultDepositApiHasChunkWithResponse(ctx context.Context, params *VaultDepositApiHasChunkParams, reqEditors ...RequestEditorFn) (*VaultDepositApiHasChunkResponse, error) {
	rsp, err := c.VaultDepositApiHasChunk(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVaultDepositApiHasChunkResponse(rsp)
}

// VaultDepositApiSendChunkWithBodyWithResponse request with arbitrary body returning *VaultDepositApiSendChunkResponse
func (c *ClientWithResponses) VaultDepositApiSendChunkWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*VaultDepositApiSendChunkResponse, error) {
	rsp, err := c.VaultDepositApiSendChunkWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVaultDepositApiSendChunkResponse(rsp)
}

// VaultDepositApiFinalizeDepositWithBodyWithResponse request with arbitrary body returning *VaultDepositApiFinalizeDepositResponse
func (c *ClientWithResponses) VaultDepositApiFinalizeDepositWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*VaultDepositApiFinalizeDepositResponse, error) {
	rsp, err := c.VaultDepositApiFinalizeDepositWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVaultDepositApiFinalizeDepositResponse(rsp)
}

func (c *ClientWithResponses) VaultDepositApiFinalizeDepositWithResponse(ctx context.Context, body VaultDepositApiFinalizeDepositJSONRequestBody, reqEditors ...RequestEditorFn) (*VaultDepositApiFinalizeDepositResponse, error) {
	rsp, err := c.VaultDepositApiFinalizeDeposit(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVaultDepositApiFinalizeDepositResponse(rsp)
}

// VaultDepositApiRegisterDepositWithBodyWithResponse request with arbitrary body returning *VaultDepositApiRegisterDepositResponse
func (c *ClientWithResponses) VaultDepositApiRegisterDepositWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*VaultDepositApiRegisterDepositResponse, error) {
	rsp, err := c.VaultDepositApiRegisterDepositWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVaultDepositApiRegisterDepositResponse(rsp)
}

func (c *ClientWithResponses) VaultDepositApiRegisterDepositWithResponse(ctx context.Context, body VaultDepositApiRegisterDepositJSONRequestBody, reqEditors ...RequestEditorFn) (*VaultDepositApiRegisterDepositResponse, error) {
	rsp, err := c.VaultDepositApiRegisterDeposit(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVaultDepositApiRegisterDepositResponse(rsp)
}

// ParseVaultDepositApiHasChunkResponse parses an HTTP response from a VaultDepositApiHasChunkWithResponse call
func ParseVaultDepositApiHasChunkResponse(rsp *http.Response) (*VaultDepositApiHasChunkResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &VaultDepositApiHasChunkResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseVaultDepositApiSendChunkResponse parses an HTTP response from a VaultDepositApiSendChunkWithResponse call
func ParseVaultDepositApiSendChunkResponse(rsp *http.Response) (*VaultDepositApiSendChunkResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &VaultDepositApiSendChunkResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseVaultDepositApiFinalizeDepositResponse parses an HTTP response from a VaultDepositApiFinalizeDepositWithResponse call
func ParseVaultDepositApiFinalizeDepositResponse(rsp *http.Response) (*VaultDepositApiFinalizeDepositResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &VaultDepositApiFinalizeDepositResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseVaultDepositApiRegisterDepositResponse parses an HTTP response from a VaultDepositApiRegisterDepositWithResponse call
func ParseVaultDepositApiRegisterDepositResponse(rsp *http.Response) (*VaultDepositApiRegisterDepositResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &VaultDepositApiRegisterDepositResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RegisterDeposit2Response
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RZbW8buRH+KwO2QIFgLSmuURTqpzv7ghMaW4aT65dzcKJ2ZyWmXHJNcu3Igf57MVzu",
	"i1art7jn3H2zV+TMPMN5eYb8ymKd5VqhcpaNvzIbLzHj/s93QnEpnvEKc22Fu8OHAq2jX3KjczROoF+X",
	"lL9PkvIfGxuRO6EVG7PJFegUHDcLdDALgmYsYk44iWzMwieR0LdVTp+EcrhAw9briBl8KITBhI1/ban5",
	"1OzfYWMtTM8/Y+zYOmJ3uBDWoQkrz1twNm2+av4j48N6cBpMEDG4V/dqqhC4SkAruQKtkNbOcm5Qud+U",
	"TvA3kcz8glmspcSY5PlvWWEdzBFskedSYDJgUcehGxu2DRQJ6bqsF4FF8yjUArgFt0QwWjvv9iWCwqcK",
	"wQCug2b9pDCB+apcXfqB9v9i0fzNwtQsuBLP3KtrXH3rsbX1Tq56Ti1im07YZf9Hg3ijE/SOJYu3zK1X",
	"ZF2799vctzMFshMup+/f/3T5cTK9AW3g3fT91U932xDr7b0A1836XTF1VPjZXCuLB+MvuEWu6vDDpPLR",
	"VuSEHAlu7yQZTI7PMpLwaR/QYP0WUpInVKrb+m+E+sx/uJ2wiD2isSXMt4PRYESe0Tkqngs2Zn8fjAbn",
	"hIm7pYcz5LkYBovs8PF8GC8L9V/6ZYG9mevQZEKhhacluiUa+A8vpIMlt5Bri9a2nFrunWMCXirl9B26",
	"wiiwjrvCoh3fqzcwm52PRrMZnAVZQm2K2hJTbrlobXmjtHtzaOO/IJfILYJFtSHrIsgSKhExd5g0hRQS",
	"jRaUdoBfhHUU0wSVS4M8WcEcUd0rgDQUycTXoychJfA4xtyB0pAWxnvKa7TMn4fxeUQFnXkEQd8PufiZ",
	"20t/Bj7NeUYet2z869GFX9CvDwWaFYuY4hnFR1PZ27HoTIFR6Ef/987SFfeLEg8FgkhQOZEKNCQ9FRKb",
	"qskhLwxCWqi4nZu0CAqVoJErKkj0zfvSO3sh9ZxLuYLCKxjs8EAq9dOk1n2CG17R7rrlSv0k2rYG71pn",
	"hFr0OfeGZ1jZBXMkbUUuNU8oIi3wPEdOe0ErKCwav9CurMNsj7/eCYn+3+O99TJD2g5IG+UH4d+h5E48",
	"IlBdq9V/O/BK3i13yxPAf6sZbdgmyMhL1Qehvz2bc4sJ1S78UkVeXBjfZstoE8p/tNQ6VeyPpyxF+3LF",
	"16CbIpuflCwvtSYTSmRFxsZvN73iV6jKmsPF5pp/ITlBpRXPSHrnK4cWUm3ALYX1Z3DIAx/E8ynhf4re",
	"vVhtqfcw0k0dfR7fB7Fc9y1Ij9JbQxx1IJbrXoi0p8bswfpROy5fCrJf5S6YjlQeja8M7yYfgMZGI2zV",
	"Og6Eq8d3WVGMYxEeqXRXrHqENa85jJFq35nBXBtiWZnI0A8NJx/mddh5AtJTVbdhZo26gwV58mH6z3+M",
	"3p6l2mTceV06ESkRS+IGTrQa5ElNieawa9p+Cod7qTHlRmKQ3OFZ0N52DW3Jqu8d33wiQ8sxxg8b56PR",
	"tonTf9OIcj666CETGi61cqj8fHfRv8TBO12oxI9ZtsgyblZszH7mFkoaTeOy7ruF+EBTAA+lmqYF7ng7",
	"/HlwSwq8NQ84XY4cg8PTzFSBLeIY7UHOT6ZUpD9M3j/qZFXeVJQOGH9lWSGdyLlxQzqVM7K3uU96vUuj",
	"iPmisCU0HFVdS9rRMxeK+3hubpVkT8REW9TjD8Iwog4jePXGH/X361dvy9HmYPBd+H/UHeb+DDNbtNm3",
	"Xqk9RdvjzHeYWqItgvK6PCTqEMDX5HlRp3f/wVr0rgeAaPvCpHMj0DMnb8+N3Tlqx9DR5efbfLZD+rp8",
	"yIdH6zb1mlrlLTe+jd5ywzPbf5G6SaTW34+weDYSGMs62r6XrW4YfZ/v5zNiobi04JbcUXkz+Ch0YeXq",
	"rHWt3RAZUeaYRIeey4R3npL5NMtibozA8tlDZLms45K0AJeySljqclzKe+WDsyycUlDboVxQiSXqVCYT",
	"LPkj+rtTsKjcAAi8V6xW1W3pvQpyeeow9M8lV4lE403nUhILsMAVoDG6fDKaJJjlmg7gCH7WgAw0LS2o",
	"ttd3udXlcLmacjPL/StVtaLtprJcYVLlaumQp6WIl6C0u1cbzvIOWKErnWAwRvFYPrx4ZnjqtfQhftl5",
	"w9vLMnleH/Lws6XIalPMvxpM2Zj9Zdi8aQ7Dg+Zwx0vhy/Lsou+nH3kCtfgTE62ysn7h6U23KmV2p1v1",
	"YGOB+0e1+mwGh06j89TzO53Grpez44/jdzIjvGt5O/pP/ITTrMS3TnO9/l8AAAD//7H5dyNyHwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
